different action

diff --git a/.github/workflows/build_docs.yml b/.github/workflows/build_docs.yml
--- a/.github/workflows/build_docs.yml
+++ b/.github/workflows/build_docs.yml
@@ -42,23 +42,30 @@ jobs:
       - name: make docs
         run: cd docs; make html
 
-      - name: commit docs
-        run: |
-          mkdir gh-pages
-          cp -r docs/build/html/* gh-pages/
-          cd gh-pages
-          touch .no_jekyll
-          git config --local user.email "action@github.com"
-          git config --local user.name "GitHub Action"
-          git add .
-          git commit -m "Update documentation" -a || true
-          # The above command will fail if no changes were present,
-          # so we ignore the return code.
+      # - name: commit docs
+      #   run: |
+      #     mkdir gh-pages
+      #     cp -r docs/build/html/* gh-pages/
+      #     cd gh-pages
+      #     touch .no_jekyll
+      #     git config --local user.email "action@github.com"
+      #     git config --local user.name "GitHub Action"
+      #     git add .
+      #     git commit -m "Update documentation" -a || true
+      #     # The above command will fail if no changes were present,
+      #     # so we ignore the return code.
 
-      - name: push to gh-pages
-        uses: ad-m/github-push-action@master
+      # - name: push to gh-pages
+      #   uses: ad-m/github-push-action@master
+      #   with:
+      #     branch: gh-pages
+      #     directory: gh-pages
+      #     github_token: ${{ secrets.GITHUB_TOKEN }}
+      #     force: true
+
+      - name: Publish to Github Pages
+        uses: peaceiris/actions-gh-pages@v4
         with:
-          branch: gh-pages
-          directory: gh-pages
           github_token: ${{ secrets.GITHUB_TOKEN }}
-          force: true
+          publish_dir: docs/build/html/
+          keep_files: false
